In [12]:
import numpy as np
import pandas as pd


def prepare_data():
    
    marathon_df = pd.read_csv("data/marathon.txt", sep="\t", names=["city", "year", "time", "seconds"])

    estPARIS = []
    estBERLIN = []
    for index, row in marathon_df.iterrows():
        if row[0] == "PARIS": 
            estPARIS.append(1)
            estBERLIN.append(0)
        elif row[0] == "BERLIN": 
            estPARIS.append(0)
            estBERLIN.append(1)
        else: 
            estPARIS.append(0)
            estBERLIN.append(0)
    
            
    marathon_df["in Paris"] = estPARIS
    marathon_df["in Berlin"] = estBERLIN
    marathon_df.drop(["city", "time"], axis=1, inplace=True)

    return marathon_df

def compute_coefficients(X, Y):
    
    X = np.mat(X)
    Y = np.mat(Y)
    # On remet la matrice Y dans le bon sens (en matrice colonne)
    Y = Y.T
    A = ((X.T * X).I) * X.T * Y
    return A

def perform_regression(dataset):
    
    x_df = dataset[["year", "in Paris", "in Berlin"]]
    y_df = dataset["seconds"]
    x_matrix = x_df.to_numpy()
    y_matrix = y_df.to_numpy()
    
    print(compute_coefficients(x_matrix, y_matrix))
    
    
df = prepare_data()
perform_regression(df)

[[2011    1    0]
 [2010    1    0]
 [2009    1    0]
 ...
 [2008    0    0]
 [2009    0    0]
 [2010    0    0]] [[ 7589  7601  7547  7600  7637  7683  7682  7736  7593  7698  7780  7729
   7690  7777  7814  7938  7806  7856  7846  7803  7990  7983  8033  7869
   7964  7849  7918  7958  8047  7904  8750  8333  9295  9041  8457  7418
   7508  7568  7439  7466  7556  7661  7604  7495  7607  7727  7662  7604
   7565  7661  7755  7622  7711  7857  7687  7857  7696  7811  7905  7871
   7863  7903  8015  8017  8087  8142  8208  8469  8403  8119  8588 10028
   9893  7704  7518  7570  7599  7612  7709  7750  7672  7753  7765  7611
   7674  7722  7648  7848  7770  7785  7731  7744  7858  7895  7974  7864
   7698  7806  7791  7800  7732  7815  7698  7785  7835  7821  7856  7955
   7809  7892  7905  7830  7971  7838  7873  7848  7777  8045  8316  8089
   8281  8179  8525  8344  8974  8641  8500  8715  8596  8695  8846  8879
   9013  9047  9626  9445  9945  8211  8328  7967  8086  7741  8291  793